name: 🐞 Bug report
description: Tell us about something that isn't working correctly
labels:
  - bug
body:
  - type: input
    attributes:
      label: Homey version
      description: Which Homey are you using and with which firmware?
      placeholder: e.g. 2023 Homey Pro, v12.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Tuya app version
      description: Which Tuya app version do you have installed on your Homey?
      placeholder: e.g. v1.0.1
    validations:
      required: true
  - type: input
    attributes:
      label: App diagnostics report ID
      description: Please generate an app diagnostics report and share it identifier
      placeholder: e.g. fff30e8b-c5d0-4916-8349-2d938ef29cae
  - type: textarea
    attributes:
      label: Description
      description: "Tell us what isn't working for you: please try to be as descriptive as possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Device specification
      description: |
        If your bug report is related to a specific device we will need some information about it. To retrieve, please:

        - Make sure you have the latest version of the Tuya Homey App installed
        - Open https://my.homey.app using a laptop/desktop
        - Add your device if you didn't already
        - Open its settings and copy the specifications from the "Device Specification" setting
        - Paste the value below

        The device specification will look like `{ "device": ..., "specifications": ..., 'data_points': ...}`. If it shows `<not available>` you can either re-add your device, or add it as other/unknown to retrieve the correct value.

        When this information is missing or incorrect, we will need to close your bug report!
